// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	repository "api-hackaton-devs/repository"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetHackatonWithBestDevs provides a mock function with given fields:
func (_m *Repository) GetHackatonWithBestDevs() (*[]repository.Hackaton, error) {
	ret := _m.Called()

	var r0 *[]repository.Hackaton
	if rf, ok := ret.Get(0).(func() *[]repository.Hackaton); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]repository.Hackaton)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertHackaton provides a mock function with given fields: h
func (_m *Repository) InsertHackaton(h *repository.Hackaton) error {
	ret := _m.Called(h)

	var r0 error
	if rf, ok := ret.Get(0).(func(*repository.Hackaton) error); ok {
		r0 = rf(h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
